services:
  trackingservice:
    image: trackingservice
    build:
      context: .
      dockerfile: TrackingService/Dockerfile

  redis:
    image: redis:7.2-alpine
    environment:
      - REDIS_PASSWORD=secret
      - TZ=Africa/Cairo
    container_name: tracking-redis
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    ports:
      - "3796:6379"